version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env

  ginapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: helseveileder
    ports:
      - 8080:8080
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - ./.env:/app/.env
    command: sh -c "wait-for-it postgres:5432 -- ./main"

volumes:
  postgres_data: