version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=helse123
      - POSTGRES_USER=admin
      - POSTGRES_DB=helseveileder
  ginapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: helseveileder
    volumes:
      - ${HOME}/helseveileder/backend/cmd/db/backups/answer_backup.csv
      - ${HOME}/helseveileder/backend/cmd/db/backups/bugreport_backup.csv
      - ${HOME}/helseveileder/backend/cmd/db/backups/evaluation_backup.csv
    depends_on:
      - postgres
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - ginapi
