version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - .env
  ginapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: helseveileder
    ports:
      - 8080:8080
    depends_on:
      - postgres
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - ginapi
