version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=helse123
      - POSTGRES_USER=admin
      - POSTGRES_DB=helseveileder
  ginapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: helseveileder
    depends_on:
      - postgres
